export function add(editor, action) {}
export function get(editor, action) {}
export function getSelected(editor, action) {}
export function getAll(editor, action) {}
export function getRoot(editor, action) {}
export function remove(editor, action) {}
export function select(editor, action) {}
export function deselect(editor, action) {}
export function move(editor, action) {}
export function update(editor, action) {}
